export const PRODUCT_REQUEST = "PRODUCT_REQUEST"
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS"
export const PRODUCT_FALURE = "PRODUCT_FALURE"

export const CATEGORY_REQUEST = "CATEGORY_REQUEST"
export const CATEGORY_SUCCESS = "CATEGORY_SUCCESS"
export const CATEGORY_FALURE = "CATEGORY_FALURE"

export const PARTICULAR_REQUEST = "PARTICULAR_REQUEST"
export const PARTICULAR_SUCCESS = "PARTICULAR_SUCCESS"
export const PARTICULAR_FALURE = "PARTICULAR_FALURE"

export const CART_REQUEST = "CART_REQUEST"
export const CART_SUCCESS = "CART_SUCCESS"
export const CART_FALURE = "CART_FALURE"


export const CART_GET_REQUEST = "CART_GET_REQUEST"
export const CART_GET_SUCCESS = "CART_GET_SUCCESS"
export const CART_GET_FALURE = "CART_GET_FALURE"

export const INCREMENT_REQUEST = "INCREMENT_REQUEST"
export const INCREMENT_SUCCESS = "INCREMENT_SUCCESS"
export const INCREMENT_FALURE = "INCREMENT_FALURE"

export const DECREMENT_REQUEST = "DECREMENT_REQUEST"
export const DECREMENT_SUCCESS = "DECREMENT_SUCCESS"
export const DECREMENT_FALURE = "DECREMENT_FALURE"

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST"
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS"
export const DELETE_CART_FALURE = "DELETE_CART_FALURE"